### PR TITLE
Nav icon tweaks

### PR DESCRIPTION
**Pull request by Nateldn**

### CODE REVIEW

**Review by damien-rembert — COMMENTED** [review]
Looks great, just two things that need editing and then I think you can go ahead and merge:
- user gallery is broken (as it's the copy of the old gallery), could you put in that one:
[userGallery.js](https://github.com/damien-rembert/pixel-FE/blob/eaf9b507fe32fa871835b0590d844bea37823d27/src/Components/UserGallery.js)

- Also in the gallery and in the userGallery, `<section class="pagination">` should be `className`

**Review by Terrys101 — APPROVED** [review]

**Comment by damien-rembert** [comment]
This looks amazing, Nate!

**Comment by Terrys101** [comment]
yeah I agree it looks nice and clean.

**Comment by Nateldn** [comment]
Just  made a couple more adjustments. I'll merge this now and fork - so I stop bothering you with approval requests. 😅

**Pull request merged**
